Feat/#30 pay check UI
Homeat/HOMEAT_iOS pull request #49
Opened 2024-04-23 17:51 UTC by befur1

## ❇️ 작업한 내용에 대해 설명해주세요

- 지출확인 캘린더 기능을 추가했습니다
- 퍼센테이지별 배경색 구현은 api 연결시에 작업하겠습니다!

## ❇️ 어떤 것을 중점으로 리뷰 해주길 바라시나요?
- 캘린더 부분을 뷰로 따로 빼서 작업했습니다

## ❇️ 공통 작업 부분에 대한 수정 사항이 있다면 적어주세요
- 

## ❇️ PR 유형
어떤 변경 사항인가요?

- [x] 새로운 기능 추가
- [x] UI 디자인 구현 혹은 변경
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항 (오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] info.plist / package 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## ❇️ Checklist
- [ ] 코드 컨벤션을 지켰나요?
- [ ] git 컨벤션을 지켰나요?
- [ ] PR 날리기 전에 검토하셨나요?

- [ ] 코드리뷰를 반영했나요?

## ❇️ 스크린샷이 있다면 첨부해주세요

![image](https://github.com/Homeat/HOMEAT_iOS/assets/145318322/c32abcb9-b371-45fe-ac25-3e8a5a10144b)

![image](https://github.com/Homeat/HOMEAT_iOS/assets/145318322/d7044f7f-d6dc-46bd-a977-49a25e4347e6)

### ❇️ Issue

Resolved #30

2024-04-24 07:35 UTC, minsolkim approved these changes
수고했소

2024-04-24 10:54 UTC, rkdtnlzl requested changes
주석 삭제 등 클린코드 부분만 수정하면 좋을거같아요!

2024-04-24 10:54 UTC, rkdtnlzl commented on HOMEAT/Presentation/HomeScene/View/CalendarView.swift
> +    //cell 높이, 넓이 설정
이런 주석같은 것들은 삭제하는 클린코드 형식으로 수정하면 좋을거같아요!

2024-04-24 12:38 UTC, insa658723 approved these changes
수고하셨습니다

2024-04-25 11:04 UTC, rkdtnlzl approved these changes
확인했습니다! 고생하셨습니다!

2024-04-25 11:58 UTC, merged