[HOMEAT-41] Feat[#65] 월뷰,주간뷰 action 리팩토링
Homeat/HOMEAT_iOS pull request #67
Opened 2024-05-12 12:47 UTC by minsolkim

## ❇️ 작업한 내용에 대해 설명해주세요

-  월 뷰 , 주간 뷰 코드 리팩토링 함 
- 서벼 연동 관계없이 back,next버튼 action이 작동되게 수정 

## ❇️ 어떤 것을 중점으로 리뷰 해주길 바라시나요?
- 코드 간격

## ❇️ 공통 작업 부분에 대한 수정 사항이 있다면 적어주세요
- 없음

## ❇️ PR 유형
어떤 변경 사항인가요?

- [ ] 새로운 기능 추가
- [ ] UI 디자인 구현 혹은 변경
- [ ] 버그 수정
- [ ] 코드에 영향을 주지 않는 변경사항 (오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] info.plist / package 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## ❇️ Checklist
- [x] 코드 컨벤션을 지켰나요?
- [x] git 컨벤션을 지켰나요?
- [x] PR 날리기 전에 검토하셨나요?

- [x] 코드리뷰를 반영했나요?

### ❇️ Issue

Resolved #65

2024-05-14 05:33 UTC, insa658723 approved these changes
수고하셨습니다

2024-05-14 09:36 UTC, befur1 reviewed
패키지 버전은 그대로 두는게 낫지 않을까요?

2024-05-14 09:36 UTC, befur1 commented on HOMEAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
패키지 버전 바뀌는 부분 굳이 머지했다가 충돌 날 것 같아서 커밋 안했으면 좋겠는데 다들 어떻게 생각하시는지 모르겠네요

2024-05-15 06:37 UTC, rkdtnlzl commented on HOMEAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
패키지수정부분은 커밋에서 제거하는게 나을거같습니다~!!

2024-05-15 06:40 UTC, rkdtnlzl requested changes
패키지 수정 커밋사항 제거해주세요~

2024-05-15 06:40 UTC, rkdtnlzl commented on HOMEAT.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "revision" : "be0c1f6f1964cfb07f9d819b0863f2c3f255f612",
패키지 버전 부분은 커밋으로 올리지 말고 머지하는걸로 할게요~!
다시 패키지 이전버전으로 돌리고 push해주세요~

2024-05-15 09:18 UTC, rkdtnlzl approved these changes
수고했으~

2024-05-16 04:27 UTC, merged